# Generated by Django 4.1.7 on 2024-05-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_product_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=25)),
                ('desc', models.CharField(max_length=300)),
                ('category', models.CharField(default='', max_length=30)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('publish', models.DateField()),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='shop')),
            ],
        ),
    ]
